SNOWFLAKE_USER = 'username'
SNOWFLAKE_PASSWORD = 'password'
SNOWFLAKE_ACCOUNT = 'account'     # e.g., xy12345.ap-south-1
SNOWFLAKE_WAREHOUSE = 'RETAIL_WH'
SNOWFLAKE_DATABASE = 'RETAIL_OPTIMIZATION'
SNOWFLAKE_SCHEMA = 'RAW_DATA'